steps:
    # install composer dependencies
    - name: 'gcr.io/$PROJECT_ID/composer'
      args: ['install', '--no-dev', '--optimize-autoloader']

    # build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/code-formatter:$COMMIT_SHA', '.']

    # push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/code-formatter:$COMMIT_SHA']

    # Deploy container image to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
      - 'run'
      - 'deploy'
      - 'code-formatter'
      - '--image'
      - 'gcr.io/$PROJECT_ID/code-formatter:$COMMIT_SHA'
      - '--region'
      - 'europe-west4'
      - '--platform'
      - 'managed'

images:
    - 'gcr.io/$PROJECT_ID/code-formatter:$COMMIT_SHA'
