version: '3'

services:
  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    image: dev-community-code-formatter_web
    ports:
      - 80:80
    volumes:
      - .:/srv/app
