name: Static analysis (phan)

on:
  pull_request:
    paths:
      - "**.php"

jobs:
  phan:
    runs-on: ubuntu-latest
    steps:
      - name: Install PHP and dependencies
        run: |
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install -y php7.4-cli php7.4-json php7.4-iconv php7.4-curl php-ast
          sudo phpenmod -v 7.4 json iconv curl ast
          sudo php -m | grep xdebug && phpdismod -v 7.4 xdebug
      - name: Install php-composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          sudo php composer-setup.php --install-dir=/usr/local/bin
          php -r "unlink('composer-setup.php');"
      - uses: actions/checkout@v2
      - name: Install composer packages
        run: composer install
      - name: Run phan from vendor folder
        run: vendor/bin/phan -S -k ./.phan/config.php
